package convertisseur;


/**
* convertisseur/EuroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Euro.idl
* Tuesday, February 18, 2025 2:49:27 PM CET
*/

public interface EuroOperations 
{
  String devise ();
  void devise (String newDevise);
  double taux ();
  void taux (double newTaux);
  double toEuro (double devise);
  double toDevise (double euro);
  void setTaux (double _taux);
  void setDevise (String _devise);
} // interface EuroOperations
