package convertisseur;


/**
* convertisseur/Euro.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Euro.idl
* Tuesday, February 18, 2025 2:49:27 PM CET
*/

public interface Euro extends EuroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Euro
