package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Hello.idl
* Tuesday, February 18, 2025 2:08:22 PM CET
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
